# -*- coding: utf-8 -*-

{
    'name': 'Sale Management',
    'version': '15.0.1',
    'summary': 'Sale Management',
    'description': """Helps to manage sale architecture for the organisation""",
    'category': 'Sales',
    'depends': ['base', 'crm_lead_ksc', 'res_localization_ksc'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/product_stock_update_ksc.xml',
        'views/product_category_ksc_views.xml',
        'views/product_ksc_views.xml',
        'views/product_uom_category_ksc_views.xml',
        'views/product_uom_ksc_views.xml',
        'views/res_partner_ksc_views.xml',
        'views/sale_order_ksc_views.xml',
        'views/sale_order_line_ksc_views.xml',
        'views/crm_team_ksc_views.xml',
        'views/crm_lead_ksc_views.xml',
        'views/crm_lead_line_ksc_views.xml',
        'views/stock_warehouse_ksc_views.xml',
        'views/stock_location_ksc_views.xml',
        'views/stock_picking_ksc_views.xml',
        'views/stock_move_ksc_views.xml',
        'views/stock_inventory_ksc_views.xml',
        'views/stock_inventory_line_ksc_views.xml',
        'views/account_tax_ksc_views.xml',
        'views/purchase_order_ksc_views.xml',
        'views/purchase_order_line_ksc_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
